DROP TABLE IF EXISTS SubrackKeys;
DROP TABLE IF EXISTS ContCardInfo; 
DROP TABLE IF EXISTS CardInfo;
DROP TABLE IF EXISTS DiscoveredTpc;
DROP TABLE IF EXISTS ControllerAlarmStatus;
DROP TABLE IF EXISTS TpnAlarmStatus;